# Arrange displays in a ROW (default, left to right) or a COLUMN (top to bottom)
ARRANGE: COLUMN

# Align ROWs at the TOP (default), MIDDLE or BOTTOM
# Align COLUMNs at the LEFT (default), MIDDLE or RIGHT
ALIGN: MIDDLE

# The default ORDER is simply the order in which the displays are discovered.
# Define your own.
ORDER:
  - 'HDMI-A-1'
  - 'eDP-1'

SCALING: FALSE

MODE:
    - NAME_DESC: HDMI-A-1
      MAX: TRUE

    - NAME_DESC: eDP-1
      MAX: TRUE

# One of: ERROR, WARNING, INFO (default), DEBUG
LOG_THRESHOLD: INFO
