# Arrange displays in a ROW (default, left to right) or a COLUMN (top to bottom)
ARRANGE: ROW

# Align ROWs at the TOP (default), MIDDLE or BOTTOM
# Align COLUMNs at the LEFT (default), MIDDLE or RIGHT
ALIGN: BOTTOM

# The default ORDER is simply the order in which the displays are discovered.
# Define your own.
ORDER:
  - 'HDMI-A-1'
  - 'eDP-1'

# Enable scaling, overrides AUTO_SCALE and SCALE
SCALING: FALSE

# Override the preferred mode.
# WARNING: this may result in an unusable display. See https://github.com/alex-courtis/way-displays#known-issues-with-workarounds
# for a possible workaround.
MODE:
    # Resolution and refresh
    - NAME_DESC: HDMI-A-1
      MAX: TRUE

    # Highest available
    - NAME_DESC: eDP-1
      MAX: TRUE

# Rotate or translate the display.
# 90, 180, 270, FLIPPED, FLIPPED-90, FLIPPED-180, FLIPPED-270
TRANSFORM:
  # - NAME_DESC: 'monitor description'
  #   TRANSFORM: 270

# VRR / adaptive sync is enabled by default. Disable it per display.
VRR_OFF:
  # - DP-2
  # - '!.*my monitor.*'


# Laptop displays usually start with eDP e.g. eDP-1. This may be overridden if
# your laptop is different.
LAPTOP_DISPLAY_PREFIX: 'eDP-1'


# One of: ERROR, WARNING, INFO (default), DEBUG
LOG_THRESHOLD: INFO


# Disable the specified displays.
DISABLED:
  #- "eDP-1"

